### ISSUE TITLE
Missing full license text

### ISSUE THREAD

**Issue by alexdima** [ralphtheninja/expand-template#10]
The MIT license explicitly requires to attach the full license text to the code or any distribution. Without this the license isn't fulfilled by the project itself and thus invalid. Also, the license requires a Copyright statement with your name and a year (see https://opensource.org/licenses/MIT).

**Comment by alexdima** [comment]
Thank you! :heart:

**Comment by ralphtheninja** [comment]
@alexandrudima De nada señor :)
