### ISSUE TITLE
the dollar character is not well supported

### ISSUE THREAD

**Issue by OlivierB-OB** [ralphtheninja/expand-template#7]
Dollar character should be escaped in the provided value to avoid the following behavior:

Pattern | Inserts
-- | --
$$ | Inserts a "$".
$& | Inserts the matched substring.
$` | Inserts the portion of the string that precedes the matched substring.
$' | Inserts the portion of the string that follows the matched substring.
$n | Where n is a positive integer less than 100, inserts the nth parenthesized submatch string, provided the first argument was a RegExp object. Note that this is 1-indexed.

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

**Comment by ralphtheninja** [comment]
The reason I released a new major was that support for node 4 was removed.

**Comment by OlivierB-OB** [comment]
Awesome! Thanks a lot!
